require: 'rubocop-rspec'

inherit_gem:
  ryu39cop:
    - 'config/rubocop.yml'
    - 'config/rspec.yml'

AllCops:
  TargetRubyVersion: 2.4
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'gemfiles/**/*'

Layout/EmptyLineBetweenDefs:
  Enabled: false

Naming/VariableNumber:
  Exclude:
    - 'spec/**/*_spec.rb'

RSpec/DescribeClass:
  Exclude:
    - 'integration_test/**/*_spec.rb'

RSpec/FilePath:
  Enabled: false
  Exclude:
    - 'spec/**/*_spec.rb'

RSpec/MultipleMemoizedHelpers:
  Enabled: false
